INT_32_MAX = 2147483647

Objects_table_defaults = {
    "id": INT_32_MAX,
    "name": "Placeholder Name",
    "placeable": 0,
    "type": "INVALID",
    "description": "Placeholder Description",
    "localize": 1,
    "npcTemplateID": None,
    "displayName": "Placeholder Display Name",
    "interactionDistance": None,
    "nametag": 0,
    "_internalNotes": "Placeholder Internal Notes",
    "locStatus": 2,
    "gate_version": None,
    "hq_valid": 1
}

RenderComponent_table_defaults = {
    "id": INT_32_MAX,
    "render_asset": "",
    "icon_asset": "",
    "IconID": 3964,
    "shader_id": 23,
    "effect1": None,
    "effect2": None,
    "effect3": None,
    "effect4": None,
    "effect5": None,
    "effect6": None,
    "animationGroupIDs": None,
    "fade": 1,
    "usedropshadow": 0,
    "preloadAnimations": 0,
    "fadeInTime": 1.0,
    "maxShadowDistance": 0.0,
    "ignoreCameraCollision": 0,
    "renderComponentLOD1": None,
    "renderComponentLOD2": None,
    "gradualSnap": 0,
    "animationFlag": None,
    "AudioMetaEventSet": None,
    "billboardHeight": None,
    "chatBubbleOffset": None,
    "staticBillboard": 0,
    "LXFMLFolder": None,
    "attachIndicatorsToNode": 0,
}

ItemComponent_table_defaults = {
    "id": INT_32_MAX,
    "equipLocation": "chest",
    "baseValue": 1000,
    "isKitPiece": 0,
    "rarity": 4,
    "itemType": 15,
    "itemInfo": 0,
    "inLootTable": 0,
    "inVendor": 0,
    "isUnique": 1,
    "isBOP": 1,  # Bind on Pickup
    "isBOE": 0,  # Bind on Equip
    "reqFlagID": 0,
    "reqSpecialtyID": 0,
    "reqSpecRank": 0,
    "reqAchievementID": 0,
    "stackSize": 1,
    "color1": 10, #TODO: figure out mapping
    "decal": None, #TODO: figure out mapping
    "offsetGroupID": None,
    "buildTypes": 0,
    "reqPrecondition": 214,
    "animationFlag": None,
    "equipEffects": None,
    "readyForQA": 0,
    "itemRating": 0,
    "isTwoHanded": 0,
    "minNumRequired": None,
    "delResIndex": None,
    "currencyLOT": None,
    "altCurrencyCost": None,
    "subItems": None,
    "audioEventUse": None,
    "noEquipAnimation": 0,
    "commendationLOT": None,
    "commendationCost": None,
    "audioEquipMetaEventSet": None,
    "currencyCosts": None,
    "ingredientInfo": None,
    "locStatus": None,
    "forgeType": None,
    "SellMultiplier": None,
}
